# fonts
font_family JetBrainsMono Nerd Font
font_size 11.5


# layout
enabled_layouts splits, stack
hide_window_decorations true

# map ctrl+[ layout_action decrease_num_full_size_windows
# map ctrl+] layout_action increase_num_full_size_windows
# map ctrl+/ layout_action mirror toggle
# map ctrl+y layout_action mirror true
# map ctrl+n layout_action mirror false

#: keymaps
#: tab
map ctrl+shift+i  set_tab_title
# map ctrl+shift+] next_tab
# map ctrl+shift+[ previous_tab
# map ctrl+shift+. move_tab_forward
# map ctrl+shift+, move_tab_backwa# rd
map alt+1        goto_tab     1 
map alt+2        goto_tab     2
map alt+3        goto_tab     3 
map alt+4        goto_tab     4 
map alt+5        goto_tab     5 
map alt+6        goto_tab     6 
map alt+7        goto_tab     7 
map alt+8        goto_tab     8 
map alt+9        goto_tab     9 
map alt+0        goto_tab     10 

# goto the previous tab you are working on
map alt+p        goto_tab     -1
map ctrl+alt+z toggle_layout stack

# the cursor animations
cursor_trail 3


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

background_opacity 0.86
dynamic_background_opacity yes
# Create a new window splitting the space used by the existing one so that
# the two windows are placed one above the other
map ctrl+shift+' launch --location=hsplit

# Create a new window splitting the space used by the existing one so that
# the two windows are placed side by side
map ctrl+shift+5 launch --location=vsplit
#: broadcast
map f1 launch --allow-remote-control kitty +kitten broadcast --match-tab state:focused
#: resizing window
map cmd+r start_resizing_window
map ctrl+shift+i resize_window wider
map ctrl+shift+m resize_window narrower
map ctrl+shift+k resize_window taller
map ctrl+shift+j resize_window shorter
map ctrl+shift+r resize_window reset

#: tab
tab_bar_edge       bottom
tab_bar_style      fade 
tab_bar_min_tabs   1
# tab_separator      " ┃ "
tab_title_template "🐖{index}.{title}"

#: ssh
share_connections yes
